name: english_xii_notes
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/chapter_logo/

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Medium.ttf

          style: italic
          weight: 700
